name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello TestBash"
