name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello TestBash"
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "cd /src/webapp/api"
      - run: echo "npm install"
      - run: echo "npm run test"
